# Generated by Django 4.2.13 on 2024-07-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flores_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.TextField()),
                ('sexo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True))
            ],
        )
    ]
